name: Deploy to Firebase Hosting on push
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          cd app
          npm ci
      - name: Build
        run: |
          cd app
          npm run build
      - name: Deploy to Firebase
        run: |
          cd app
          npx firebase-tools deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
