name: Deploy to Firebase Hosting on push
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build in Docker
        run: |
          docker-compose up -d
          docker exec front sh -c "npm ci"
          docker exec front sh -c "npm run build"
      - name: Copy build artifacts
        run: docker cp front:/app/dist ./dist
      - name: Deploy to Firebase
        run: npx firebase-tools deploy --only hosting --project react-news-db-7c0b7 --token ${{ secrets.FIREBASE_TOKEN }}
